OPTS=""
OPTS+=" --exclude='.git/'"
OPTS+=" --exclude='processed_data'"
OPTS+=" --exclude='checkpoints'"
OPTS+=" --exclude='downstream_data'"
OPTS+=" --exclude='pretrain_data'"
OPTS+=" --exclude='processed_data'"
OPTS+=" --exclude='processed_data_1'"
OPTS+=" --exclude='results'"
OPTS+=" --exclude='*__pychache__/*'"
OPTS+=" --exclude='*.egg-info'"
OPTS+=" --exclude='*.pyc'"
OPTS+=" --exclude='azcopy'"
OPTS+=" --exclude='send.sh'"
OPTS+=" --exclude='wandb'"

ft syncd "./" -a "-avzP $OPTS "